### PR TITLE
flake with overlay for cln

### PR DESCRIPTION
**Pull request by jurraca**
This isn't fully right, but if you want to use a different version of CLN in your repo, you would use an overlay like this. Basically, you change the `src` attribute of the nixpkgs `clightning` package to point to lisa's onchain-notif branch and create a package and devshell from there. I can't seem to get the `eachDefaultSystem` thing to work correctly but this should get you started.

### CODE REVIEW

**Comment by chrisguida** [comment]
How can I recreate this?

`I can't seem to get the eachDefaultSystem thing to work correctly but this should get you started.`

I'm actually not seeing any errors now since my fix.

**Comment by jurraca** [comment]
cleaned up some stuff and been hitting my head against a wall with this overlay -- it works but it's not pulling the right CLN version from nifty's fork and I have no clue why. I'm fairly sure this is the right syntax...

**Comment by chrisguida** [comment]
What's still left to do on this?

Also I noticed that the build isn't working anymore without `openssl`, can you add that back?

**Comment by jurraca** [comment]
todo:
- figure out why the overlay doesn't work: the devshell currently provides the nixpkgs version of `clightning` (v23.05.2) instead of the nifty's fork version we're attempting to overlay.
- remove the template boilerplate (`default.nix`, `shell.nix`)
- include CI to test different platforms
- add nix tests that include the plugin (integration tests btw cln and smaug)

**Comment by jurraca** [comment]
i get it now --  this has been working fine actually. I was just checking the version of the binary it output via the command line. the version is a set string in the upstream / nixpkgs `clightning/default.nix` expression, so it stayed the same with the overlay. We need to override it as well. see prev [commit](https://github.com/chrisguida/smaug/pull/23/commits/8d45b30f426ebde7a0aac10208c5e66a1061e281)

**Comment by chrisguida** [comment]
Yep, builds! It was building before for me too, but now it has the version you added. Not sure if we should stick with this since the version is actually a special commit on a special fork, but it's definitely closer than before!

I added `bitcoind` to the dev shell so that we can immediately run `source contrib/startup_regtest.sh` from the lightning repo (currently you need to have this checked out... any way we can add it to the smaug repo here without duplicating the source for the bash script?)

This is very close to being done!

**Comment by chrisguida** [comment]
Another thing I'd like to add if possible is a `cargo build` of smaug itself, and a command to start the plugin, possibly with our own override of `startup_regtest.sh`... what do you think?

**Comment by chrisguida** [comment]
Perhaps the dev should be expected to run `cargo build`? so maybe just the `l1-cli plugin start` bash alias?

**Comment by jurraca** [comment]
> Another thing I'd like to add if possible is a cargo build of smaug itself

`nix develop` then `cargo build`

> possibly with our own override of startup_regtest.sh

so `contrib/startup_regtest.sh` lives in the clightning repo. It should be possible to copy the script file by modifying its buildPhase or something but i haven't figured it out yet.

**Comment by jurraca** [comment]
thanks to @samrose for the assist

**Pull request merged**
